version: '3'
services:
  wordpress:
    build: ./wordpress
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: wp
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
volumes:
  db_data:

